COmment out code

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -105,43 +105,43 @@ jobs:
           draft: true
           prerelease: false
 
-      - name: Upload release asset
-        id: upload-release-asset 
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          # This pulls from the "Create release entry" step above, referencing it's ID to get its outputs object, 
-          # which include a `upload_url`. See this blog post for more info: 
-          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
-          upload_url: ${{ steps.create-release.outputs.upload_url }} 
-          # asset_path: ./dxCompiler${{ github.event.inputs.release-version }}.jar
-          asset_path: ./executorWdl/src/main/resources/application.conf
-          asset_name: dxCompiler-${{ github.event.inputs.release-version }}.jar
-          # asset_content_type: application/jar
-          asset_content_type: text/html
-
-      - name: Push main and tag to origin if successful
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          export PATH="$PATH:$HOME/.local/bin"
-          # git push origin ${{ github.ref }}
-          # git push origin tagname
-          echo ${{ steps.create-release.outputs.id }}
-
-      # - name: Push tag to origin if successful
-      #   if: ${{ success() }}
-      #   uses: ad-m/github-push-action@master
+      # - name: Upload release asset
+      #   id: upload-release-asset 
+      #   uses: actions/upload-release-asset@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     branch: ${{ github.event.inputs.release-version }}
+      #     # This pulls from the "Create release entry" step above, referencing it's ID to get its outputs object, 
+      #     # which include a `upload_url`. See this blog post for more info: 
+      #     # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
+      #     upload_url: ${{ steps.create-release.outputs.upload_url }} 
+      #     # asset_path: ./dxCompiler${{ github.event.inputs.release-version }}.jar
+      #     asset_path: ./executorWdl/src/main/resources/application.conf
+      #     asset_name: dxCompiler-${{ github.event.inputs.release-version }}.jar
+      #     # asset_content_type: application/jar
+      #     asset_content_type: text/html
 
-      - name: Rollback release if unsuccessfull
-        if: ${{ cancelled() || failure() || success() }}
-        uses: author/action-rollback@stable
-        with:
-          release_id: ${{ steps.create-release.outputs.id }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Push main and tag to origin if successful
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #   run: |
+      #     export PATH="$PATH:$HOME/.local/bin"
+      #     # git push origin ${{ github.ref }}
+      #     # git push origin tagname
+      #     echo ${{ steps.create-release.outputs.id }}
+
+      # # - name: Push tag to origin if successful
+      # #   if: ${{ success() }}
+      # #   uses: ad-m/github-push-action@master
+      # #   with:
+      # #     github_token: ${{ secrets.GITHUB_TOKEN }}
+      # #     branch: ${{ github.event.inputs.release-version }}
+
+      # - name: Rollback release if unsuccessfull
+      #   if: ${{ cancelled() || failure() || success() }}
+      #   uses: author/action-rollback@stable
+      #   with:
+      #     release_id: ${{ steps.create-release.outputs.id }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
