Print tags

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -121,28 +121,23 @@ jobs:
       #     # asset_content_type: application/jar
       #     asset_content_type: text/html
 
-      # - name: Push main and tag to origin if successful
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #   run: |
-      #     export PATH="$PATH:$HOME/.local/bin"
-      #     # git push origin ${{ github.ref }}
-      #     # git push origin tagname
-      #     echo ${{ steps.create-release.outputs.id }}
-
-      # # - name: Push tag to origin if successful
-      # #   if: ${{ success() }}
-      # #   uses: ad-m/github-push-action@master
-      # #   with:
-      # #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      # #     branch: ${{ github.event.inputs.release-version }}
-
-      - name: Rollback release if unsuccessfull
-        if: ${{ cancelled() || failure() || success() }}
-        uses: author/action-rollback@stable
-        with:
-          release_id: ${{ steps.create-release.outputs.id }}
-          always_delete_tag: true
+      - name: Push main and tag to origin if successful
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          export PATH="$PATH:$HOME/.local/bin"
+          # git push origin ${{ github.ref }}
+          # git push origin tagname
+          git tag | grep 2.2.0
+          echo ${{ steps.create-release.outputs.id }}
+
+
+
+      # - name: Rollback release if unsuccessfull
+      #   if: ${{ cancelled() || failure() || success() }}
+      #   uses: author/action-rollback@stable
+      #   with:
+      #     release_id: ${{ steps.create-release.outputs.id }}
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
